name: haircutmen_user_app
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  get: ^4.7.2
  dio: ^5.8.0+1
  pretty_dio_logger: ^1.4.0
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.2.0
  google_fonts: ^6.2.1
  shared_preferences: ^2.5.3
  mime: ^2.0.0
  flutter_local_notifications: ^18.0.0
  socket_io_client: ^3.1.2
  cached_network_image: ^3.4.1
  intl_phone_field: ^3.2.0
  image_picker: ^1.1.2
  pin_code_fields: ^8.0.1
  intl: ^0.20.2
  flutter_html: ^3.0.0
  flutter_dotenv: ^6.0.0
  image_cropper: ^11.0.0
  curved_navigation_bar: ^1.0.6
  table_calendar: ^3.2.0
  get_storage: ^2.1.1
  share_plus: ^12.0.0
  qr_flutter: ^4.1.0
  webview_flutter: ^4.13.0
  country_picker: ^2.0.24
  url_launcher: ^6.3.0
  flutter_launcher_icons: ^0.14.4
  translator: ^1.0.4+1
  http: ^1.6.0



dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/H - Full black.svg"


  flutter_lints: ^5.0.0

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - .env

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
